config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root "posts#index"
  resources :users, only: %i(index show)
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, shallow: true
  end
  resources :streams
  resources :rooms
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/model.rb
class Model < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}
  scope :order_created_desc, lambda { order("created_at desc")}
  
  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end

  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :likes
  has_many :streams
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name ,:image])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def like_params
    params.permit :post_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    render "shared/_login" if !user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: [:show, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.all.includes(:photos, :user, :likes).order_created_desc.limit(10)
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if params[:images]
        params[:images].each do |img|
          @post.photos.create(image: params[:images][img])
        end
      end
      redirect_to posts_path
      flash[:notice] = "Successfully created..."
    else
      flash[:alert] = "Something went wrong..."
      redirect_to posts_path  
    end
  end
  
  def show
    @likes = @post.likes.includes(:user)
    @is_liked = @post.is_liked(current_user)
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to posts_path
  end

  private 

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    flash[:danger] = "Post not exits..."
    redirect_to root_path
  end
  
  def post_params
    params.require(:post).permit :content
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    if params[:password].blank?
      resource.update_without_password params
    else
      resource.update params
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :config_opentok,:except => [:index]
    def index
      @rooms = Room.where(:public => true)
      @room = Room.new
    end
    
    def create
      session = @opentok.create_session
      params[:room][:session_id] = session.session_id
  
      @room = current_user.rooms.build(room_params)
  
      respond_to do |format|
        if @room.save
          format.html { redirect_to("/party/"+@room.id.to_s) }
        else
          format.html { render :controller => 'rooms',
            :action => "index" }
        end
      end
    end
  
    def destroy
      @room = Room.find_by id: params[:id]
      @room.destroy
      redirect_to rooms_path
    end
  
    def party
      @room = Room.find(params[:id])
  
      @tok_token = @opentok.generate_token(@room.session_id)
    end
  
    private
    def config_opentok
      if @opentok.nil?
        @opentok = OpenTok::OpenTok.new("46236752", "bbb800d7c2ee9486b32ff174ed0996fb96feadf3")
      end
    end
  
    def room_params
      params.require(:room).permit(:title, :public, :session_id)
    end
  end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
    before_action :config_opentok,:except => [:index]
    def index
      @streams = Stream.all
      @new_stream = Stream.new
    end
  
    def create
        session = session = @opentok.create_session
        params[:stream][:session_id] = session.session_id
        @new_stream = current_user.streams.build(stream_params)
        # @new_post.session_id = session.session_id
  
      respond_to do |format|
        if @new_stream.save
          format.html { redirect_to("/streams/"+@new_stream.id.to_s) }
        else
          format.html { render :controller => 'rooms',
            :action => "index" }
        end
      end
    end

    def destroy
      @stream = Stream.find_by id: params[:id]
      if @stream.destroy
         redirect_to root_path
      else
        redirect_to root_path
      end
    end

    def show 
      @stream = Stream.find_by id: params[:id]
      @tok_token = @opentok.generate_token(@stream.session_id)
    end

    private
    def config_opentok
      if @opentok.nil?
       @opentok = OpenTok::OpenTok.new("46236752", "bbb800d7c2ee9486b32ff174ed0996fb96feadf3")
      end
    end
  
    def stream_params
      params.require(:stream).permit(:title,:session_id)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user
    return user.image if user.image
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="https://assets.tokbox.com/solutions/css/style.css">
  </head>

  <body>
    <%= render "shared/navbar" if current_user %>
    <div class="container">
      <%= yield %>
    </div>
    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value|%>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>  
      </script>
    <% end %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "Love", like_path(@like), method: :delete, remote: true, class: "core-sprite loved hide-text" %>');
console.log("create like success");

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "Loved", post_likes_path(@post), method: :post, remote: true, class: "core-sprite love hide-text" %>');
console.log("delete like success");

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text" %>
<% end %>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
  <% if post.photos.size == 1 %>
    <%= image_tag post.photos.first.image, class: "card-img-top" %>
  <% else %>
    <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
      <div class="carousel-inner">
        <% post.photos.each do |photo| %>
          <% if photo == post.photos.first %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
              <%= image_tag photo.image, class: "card-img-top" %>
            </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div class="card mt-3 post">
  <div class="card-header d-flex align-items-center">
    <%= link_to user_path(post.user), class: "no-text-decoration" do %>
      <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
    <% end %>
    <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
      title: post.user.name do %>
      <strong><%= post.user.name %></strong>
      <span class="light-color post-time"><%= time_ago_in_words(post.created_at)%> ago</span>
      <br>
      <%= post.content %>
    <% end %>
    <% if post.is_belongs_to? current_user %>
      <%= link_to post_path(post), method: :delete, 
        class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
        <i class="far fa-trash-alt" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
  <%= render "photos", post: post %>
  <div class="card-body">
    <div class="row actions">
      <div id="like-icon-post-<%= post.id.to_s%>">
        <%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
      <div class="align-self-center">
        <%= render "photos", {post: @post} %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
        <% end %>
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>
        <% if @post.is_belongs_to? current_user %>
          <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <div class="comment-list py-2">
        <% if @post.content.present? %>
          <div>
            <span><strong><%= @post.user.name %></strong></span>
            <span><%= @post.content %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<div style="min-height:700px">
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row">
    <div class="col-xl-6">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">Create Room</button>
    </div>
    </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_for (@room) do |f| %>
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Create Room</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 post-card">
              <div class="form-group row mt-2">
                <div class="col-auto pr-0">
                  <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
                </div>
                <div class="col pl-0">
                  <%= f.text_field :title, class: "form-control border-0",
                    placeholder: "Say something about this ..." %>
                </div>
                
              </div>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 post-card" style="padding-left:75px">
              Public? <%= f.check_box :public %><br/>
            </div>
          </div>
          <div class="modal-footer">
            <div class="btn-group btn-group-lg" role="group">
              <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
              <%= f.submit "Create", class: "btn btn-outline-dark" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <br>
  
</div>
<h3 style="">All group created recently in public</h3>
<% @rooms.each do |room| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(room.user), class: "no-text-decoration" do %>
      <%= image_tag avatar_url(room.user), class: "post-author-icon" %>
      <% end %>
      <%= link_to user_path(room.user), class: "normal-color no-text-decoration",
        title: room.user.name do %>
        <strong><%= room.user.name %></strong>
        <span class="light-color post-time"><%= time_ago_in_words(room.created_at)%> ago</span>
        <br>
        <%= room.title %>
      <% end %>
      <% if current_user.id == room.user.id %>
        <%= link_to room_path(room), method: :delete, 
          class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
      
    </div>
    <div class="row" style="padding: 10px 80px">
      <a href="/party/<%= room.id %>">Join</a>
    </div>
  </div>
<% end %>
</div>
<%= render "shared/footer" %>

app/views/rooms/party.html.erb
<div style="margin-top:15px" >
  <%= link_to user_path(current_user), class: "no-text-decoration" do %>
    <%= image_tag avatar_url(current_user), class: "post-author-icon" %> <%= current_user.name %>
  <% end %>
</div>
<div class="row">
  <div class="col-xs-6">
    <div id="videobox" style="margin-top:15px">
    </div>
  </div>
  <div class="col-xs-6" style="margin:15px">
    <% if current_user.id == @room.user_id %>
      <%= link_to "Stop", rooms_path(@room), method: :delete, data: {confirm: "Are you sure???"} %>
    <% else %>
      <%= link_to "Stop", root_path%>
    <% end %>
  </div>
</div>

<script src="https://static.opentok.com/v2/js/opentok.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    var apiKey =  "46236752";
    var sessionId = "<%= @room.session_id %>";
    var token = "<%= @tok_token %>";
    var session;
  
  
  TB.setLogLevel(TB.DEBUG);
  
    var session = TB.initSession(sessionId);
      session.addEventListener('sessionConnected', sessionConnectedHandler);
      session.addEventListener('streamCreated', streamCreatedHandler);
      session.connect(apiKey, token);
  var publisher;
      function sessionConnectedHandler(event) {
        publisher = TB.initPublisher(apiKey, 'videobox');
        session.publish(publisher);
        subscribeToStreams(event.streams);
      }
      function streamCreatedHandler(event) {
        subscribeToStreams(event.streams);
      }
      function subscribeToStreams(streams) {
        for (var i = 0; i < streams.length; i++) {
          if (streams[i].connection.connectionId == session.connection.connectionId) {
            return;
          }
          var div = document.createElement('div');
          div.setAttribute('class', 'col-xs-6');
          div.setAttribute('id', 'stream' + streams[i].streamId);
          document.body.appendChild(div);
          var options = {width: 700, height: 538};
          session.subscribe(streams[i], div.id, options);
        }
      }
</script>

<style type="text/css" media="screen">

  div.OT_subscriber{
    font-family: helvetica, arial, sans-serif;
    border: 1px solid rgba(87, 193, 228, .85);
    border-radius: 6px;
    margin-top: 15px;
    margin-left: 700px;
  }

</style>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_login.html.erb
<%= link_to "login", user_session_path %>
<%= link_to "sign up", new_user_registration_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to  "Navbar", root_path, class: "navbar-brand core-sprite hide-text" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-md-auto">
      <li class="nav-item">
          <%= link_to user_path(current_user.id), title:"Your Profile" do %>
            <%= fa_icon "user" %>
          <% end %>
      </li>
      <li class="nav-item">
        <%= link_to streams_path, title:"Livestreams" do %>
          <%= fa_icon "tv" %>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to rooms_path, title:"Video Call"  do %>
          <%= fa_icon "video" %>
        <% end %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/streams/index.html.erb
<div style="min-height:700px">
<h3 style="">All Stream Now</h3>
<% @streams.each do |stream| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(stream.user), class: "no-text-decoration" do %>
      <%= image_tag avatar_url(stream.user), class: "post-author-icon" %>
      <% end %>
      <%= link_to user_path(stream.user), class: "normal-color no-text-decoration",
        title: stream.user.name do %>
        <strong><%= stream.user.name %></strong>
        <span class="light-color post-time"><%= time_ago_in_words(stream.created_at)%> ago</span>
        <br>
        <%= link_to stream.title, stream_path(stream)%>
      <% end %>
      <% if current_user.id == stream.user.id %>
        <%= link_to stream_path(stream), method: :delete, 
          class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
      
    </div>
    <% if current_user.id =! stream.user.id %>
      <div class="row" style="padding: 10px 80px">
        <%= link_to "Watch", stream_path(stream)%>
      </div>
    <% end %>
  </div>
<% end %>
</div>
<%= render "shared/footer" %>

app/views/streams/show.html.erb
 <script src="https://static.opentok.com/v2/js/opentok.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    var apiKey =  "46236752";
    var sessionId = "<%= @stream.session_id %>";
    var token = "<%= @tok_token %>";
    var session;
      TB.setLogLevel(TB.DEBUG);
        var session = TB.initSession(sessionId);
          var a = <%= current_user.id %>;
          var b = <%= @stream.user_id %>;
          if ( a == b) {
            session.addEventListener('sessionConnected', sessionConnectedHandler);
          } else {
            greeting = "Good evening";
          }
          
          session.addEventListener('streamCreated', streamCreatedHandler);
          session.connect(apiKey, token);
      var publisher;
      function sessionConnectedHandler(event) {
        publisher = TB.initPublisher(apiKey, 'videobox',{width:1100, height:670});
        session.publish(publisher);
        
        subscribeToStreams(event.streams);
      }
      function streamCreatedHandler(event) {
       
        subscribeToStreams(event.streams);
      }
      function subscribeToStreams(streams) {
        for (var i = 0; i < streams.length; i++) {
          if (streams[i].connection.connectionId == session.connection.connectionId) {
            return;
          }
          var div = document.createElement('div');
          div.setAttribute('id', 'stream' + streams[i].streamId);
          document.body.appendChild(div);
          var options = {width: 1100, height: 670};
          session.subscribe(streams[i], 'containerElementId' , options);
        }
      }
  </script>
<% if current_user.id == @stream.user_id %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(@stream.user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(@stream.user), class: "post-author-icon" %>
      <% end %>
      <%= link_to user_path(@stream.user), class: "normal-color no-text-decoration",
        title: @stream.user.name do %>
        <strong><%= @stream.user.name %></strong>
        <span class="light-color post-time"><%= time_ago_in_words(@stream.created_at)%> ago</span>
        <br>
        <%= @stream.title %>
      <% end %>
      <% if current_user.id == @stream.user_id %>
        <%= link_to stream_path(@stream), method: :delete, 
          class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
    
    <div id="videobox" style="width: 900px; height: 670px;">
  </div>
<% else %>
  <div class="card mt-3 post">
  <div class="card-header d-flex align-items-center">
    <%= link_to user_path(@stream.user), class: "no-text-decoration" do %>
      <%= image_tag avatar_url(@stream.user), class: "post-author-icon" %>
    <% end %>
    <%= link_to user_path(@stream.user), class: "normal-color no-text-decoration",
      title: @stream.user.name do %>
      <strong><%= @stream.user.name %></strong>
      <span class="light-color post-time"><%= time_ago_in_words(@stream.created_at)%> ago</span>
      <br>
      <%= @stream.title %>
    <% end %>
    <% if current_user.id == @stream.user_id %>
      <%= link_to streams_path(@stream), method: :delete, 
        class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
        <i class="far fa-trash-alt" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

<style type="text/css" media="screen">

  div.OT_subscriber{
    font-family: helvetica, arial, sans-serif;
    border: 1px solid rgba(87, 193, 228, .85);
    border-radius: 6px;
    margin-top: 15px;
    margin-left: 380px;
  }

</style>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user), class: "round-img", width: "152", height: "152" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button> 
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <%= link_to "Change profile", edit_user_registration_path, class: "list-group-item list-group-item-action" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
      
    </div>
    <p class="username"><%= @user.posts.count %> Posts</p>
  </div>

<div class= "row">
<div class= "">
<% @posts.each do |post| %>
  <div class="card mt-3 post">
  <div class="card-header d-flex align-items-center">
    <%= link_to user_path(post.user), class: "no-text-decoration" do %>
      <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
    <% end %>
    <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
      title: post.user.name do %>
      <strong><%= post.user.name %></strong>
      <span class="light-color post-time"><%= time_ago_in_words(post.created_at)%> ago</span>
      <br>
      <%= post.content %>
    <% end %>
    <% if post.is_belongs_to? current_user %>
      <%= link_to post_path(post), method: :delete, 
        class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "Are you sure???"} do %>
        <i class="far fa-trash-alt" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
  <%= link_to post_path(post) do %>
    <% if post.photos.size == 1 %>
      <%= image_tag post.photos.first.image, class: "card-img-top" %>
    <% else %>
        <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
          <div class="carousel-inner">
            <% post.photos.each do |photo| %>
              <% if photo == post.photos.first %>
                <div class="carousel-item active">
              <% else %>
                <div class="carousel-item">
              <% end %>
                  <%= image_tag photo.image, class: "card-img-top" %>
                </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>
</div>
</div>

</div>

<%= render "shared/footer" %>